version: "2.4"
services:

  server:
    image: subterranwars/phoenix:bleeding
    ports:
      - "6001:8081"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/phoenix
        SPRING_DATASOURCE_USERNAME: phoenix_user
        SPRING_DATASOURCE_PASSWORD: phoenix_password
    networks:
      - stw
    depends_on:
      db:
        condition: service_healthy
    restart: always

  ui:
    image: subterranwars/phoenix-ui:bleeding
    ports:
      - "6002:80"
    networks:
      - stw
    depends_on:
      server:
        condition: service_healthy
    restart: always

  db:
    image: postgres:11
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: phoenix_user
      POSTGRES_PASSWORD: phoenix_password
      POSTGRES_DB: phoenix
    networks:
      - stw
    restart: always

networks:
  stw:
