version: "2.4"
services:

  server:
    image: subterranwars/phoenix:bleeding
    ports:
      - "6001:8081"
    networks:
      - stw
    restart: always

  ui:
    image: subterranwars/phoenix-ui:bleeding
    ports:
      - "6002:80"
    networks:
      - stw
    depends_on:
      server:
        condition: service_healthy
    restart: always

networks:
  stw:
